aks resource group: now is founded via cli and not more a parameter

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -23,9 +23,6 @@ inputs:
   aks_name:
     description: "AKS name"
     required: true
-  aks_resource_group:
-    description: "AKS resource group"
-    required: true
 
 
 runs:
@@ -53,13 +50,20 @@ runs:
         shell: bash
         run: |
           echo "🎓 Configure kubeconfig"
-          echo "[INFO] Get kubernetes credentials via az aks get-credentials"
-          export KUBECONFIG_PATH=~/.kube
-          az aks get-credentials -g ${{ inputs.aks_resource_group }} -n ${{ inputs.aks_name }} -f ${KUBECONFIG_PATH}/config-${{ inputs.aks_name }} --only-show-errors
 
-          echo "[INFO] Convert kubeconfig via kubelogin"
+          aks_resource_group=$(az aks list -o tsv --query "[?contains(name,'${{ inputs.aks_name }}')].resourceGroup" 2>/dev/null | tr -d '\r')
+          if [[ -z "$aks_resource_group" ]]; then
+            echo "❌ aks resource group not found"
+            exit 1
+          fi
+          echo "✅ Calculated aks resource group"
+
+          export KUBECONFIG_PATH=~/.kube
+          az aks get-credentials -g ${aks_resource_group} -n ${{ inputs.aks_name }} -f ${KUBECONFIG_PATH}/config-${{ inputs.aks_name }} --only-show-errors
+          echo "✅ Get kubernetes credentials via az aks get-credentials"
+
+          echo "⏳ Convert kubeconfig via kubelogin"
           export KUBECONFIG=${KUBECONFIG_PATH}/config-${{ inputs.aks_name }}
-          # kubelogin convert-kubeconfig -l spn --client-id "${{ inputs.client_id }}" --client-secret "${{ inputs.client_secret }}"
           kubelogin convert-kubeconfig -l azurecli
           echo "✅ Kubeconfig converted correctly via kubelogin and saved into ${KUBECONFIG_PATH}/config-${{ inputs.aks_name }}"
 
